### ISSUE TITLE
Please make your roadmap link public shared during WiT Hackathon

### ISSUE THREAD

**Issue by RN0311** [AyushiNayak/helping-hand#8]
Hey dear,

Just a brief intro : I'm WiT India Forum coordinator.
Issue : Your roadmap link and other docs supported link is not public, our jury will not be able to evaluate it unless it is public. Please resolve asap.

**Comment by AyushiNayak** [comment]
I am able to open all links in GitHub repo since  made it a public
repository ,I would really appreciate if you can clarify exactly which link
you are not able to access?


Thanks,
Ayushi

**Comment by RN0311** [comment]
Hey, I don't know now I am able to access the roadmap docs link, thanks much.
